facebook:
  client:
    clientId: 564162601158748
    clientSecret: dd56c82cf93b958f1d00e30b355df0c2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fileds=id,name,email,link

google :
  client :
    clientId : 531083614299-40lvfkln6kmihd62igmag5551ook21bo.apps.googleusercontent.com
    clientSecret: Q0sFH7FeoZKfbx910iTIpNmm
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao:
  client:
    clientId: 0a7ca146321bc1d63285c916ab12134c
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    resource:
      userInfoUri: https://kapi.kakao.com/v1/user/me